foreach($f in gci 1_Pcap *.pcap)
{
    # Split All Layers
    0_Tool\SplitCap_2-1\SplitCap -p 50000 -b 50000 -s session -r $f.FullName -o 2_Session\AllLayers\$($f.BaseName)-ALL
    # 0_Tool\SplitCap_2-1\SplitCap -p 50000 -b 50000 -r $f.FullName -s flow -o 2_Session\AllLayers\$($f.BaseName)-ALL
    gci 2_Session\AllLayers\$($f.BaseName)-ALL | ?{$_.Length -eq 0} | del

    # # Split Layer 7
    # 0_Tool\SplitCap_2-1\SplitCap -p 50000 -b 50000 -r $f.FullName -o 2_Session\L7\$($f.BaseName)-L7 -y L7
    # # 0_Tool\SplitCap_2-1\SplitCap -p 50000 -b 50000 -r $f.FullName -s flow -o 2_Session\L7\$($f.BaseName)-L7 -y L7
    # gci 2_Session\L7\$($f.BaseName)-L7 | ?{$_.Length -eq 0} | del

    # --- MOVED INSIDE THE LOOP ---
    # Perform finddupe cleanup immediately after processing the current file ($f)
    Write-Host "Cleaning up duplicates for file: $($f.BaseName)"
    0_Tool\finddupe -del 2_Session\AllLayers\$($f.BaseName)-ALL
    # 0_Tool\finddupe -del 2_Session\L7\$($f.BaseName)-L7
    # Note: I modified the paths here to target only the files generated by the current $f, 
    # assuming finddupe needs a specific file/folder path as an argument if it's not meant to run recursively on the whole directory.
    # If finddupe -del 2_Session\AllLayers works as intended by removing duplicates within that *directory*,
    # you might need to adjust how you call it based on what it expects for per-file cleanup.
    # If finddupe needs to run on the *entire* directory contents each time, use the original commands:
    # 0_Tool\finddupe -del 2_Session\AllLayers
    # 0_Tool\finddupe -del 2_Session\L7
}

# Original commands removed from here as they are now inside the loop
# 0_Tool\finddupe -del 2_Session\AllLayers
# 0_Tool\finddupe -del 2_Session\L7